// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGTeYdkI3cMDGvkpKywIQmH_vScEIYoh8',
    appId: '1:243067162410:ios:3d898f1f49f32d60c8d853',
    messagingSenderId: '243067162410',
    projectId: 'botroad-cd',
    storageBucket: 'botroad-cd.firebasestorage.app',
    androidClientId: '243067162410-8k9m55g0kpbrufn43dni4ak0hcqa613c.apps.googleusercontent.com',
    iosClientId: '243067162410-mal1qg08cl00a9m7jrior879vub4d0if.apps.googleusercontent.com',
    iosBundleId: 'com.example.botroad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGTeYdkI3cMDGvkpKywIQmH_vScEIYoh8',
    appId: '1:243067162410:ios:3d898f1f49f32d60c8d853',
    messagingSenderId: '243067162410',
    projectId: 'botroad-cd',
    storageBucket: 'botroad-cd.firebasestorage.app',
    androidClientId: '243067162410-8k9m55g0kpbrufn43dni4ak0hcqa613c.apps.googleusercontent.com',
    iosClientId: '243067162410-mal1qg08cl00a9m7jrior879vub4d0if.apps.googleusercontent.com',
    iosBundleId: 'com.example.botroad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmW_fp32q3OdAmx9g46x6qDFt6yhHZGpQ',
    appId: '1:243067162410:web:89c60ad4718d850fc8d853',
    messagingSenderId: '243067162410',
    projectId: 'botroad-cd',
    authDomain: 'botroad-cd.firebaseapp.com',
    storageBucket: 'botroad-cd.firebasestorage.app',
    measurementId: 'G-1D44GT2RFH',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5wlpQDowuT5Yj53kAbu7yfdXp7nhJ33g',
    appId: '1:243067162410:web:0194cc8a50a384a9c8d853',
    messagingSenderId: '243067162410',
    projectId: 'botroad-cd',
    authDomain: 'botroad-cd.firebaseapp.com',
    storageBucket: 'botroad-cd.firebasestorage.app',
    measurementId: 'G-VZYHGBDZQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnylsbegpS54XLHyWLM62TbX9jrXV57tU',
    appId: '1:243067162410:android:efc07725a645540bc8d853',
    messagingSenderId: '243067162410',
    projectId: 'botroad-cd',
    storageBucket: 'botroad-cd.firebasestorage.app',
  );

}